# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
    default_locale: en_FR

    orm:
        default:
            blameable: true
            timestampable: true
            loggable: true
            sluggable: true
            softdeleteable: true
            sortable: true
            translatable: false
            tree: false
            uploadable: false