twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
    - 'bootstrap_5_layout.html.twig'
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    - '@FMElfinder/Form/elfinder_widget.html.twig'
    - 'form_theme/fields.html.twig'
  globals:
    default_locale: '%locale%'

when@test:
  twig:
    strict_variables: true
