vich_uploader:
  db_driver: orm

  mappings:
    images:
      uri_prefix: /uploads/elfinder/images
      upload_destination: '%kernel.project_dir%/public/uploads/elfinder/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: true
      delete_on_remove: false